### PR TITLE
Proj02

### PR DESCRIPTION
**Pull request by otv5**
Completed 1100 points.

### CODE REVIEW

**Comment by fliang97** [comment]
Sorry I noticed that we didn't specify the issues that were solved during proj02
Issue #1: Display the beat (350 points)
Issue #2: Improve Readme file (100 points)

Since we have done a total of 650 points in proj01, so accumulatively we have done 1100 points.

**Comment by rhelmot** [comment]
You also really should remove all those .ds_store files...

**Comment by fliang97** [comment]
Sorry, I am not so sure what you are talking about. What should I do to fix the problem?

**Comment by rhelmot** [comment]
Also, uh, there were only 550 points possible in proj01...

**Comment by fliang97** [comment]
I noticed that. Is there any chance to improve proj01 and get the remaining 60 points since we only got 490 points in proj01?

**Comment by rhelmot** [comment]
No. You are supposed to compensate for the loss by getting the 100 extra credit points possible for going above 500 in proj02.

**Comment by rhelmot** [comment]
image

This probably looks a little different for you, but you should have some indicator that the pull request can't be merged. You need to fix the merge conflicts. You should make a branch which is a copy of my upstream master branch (`git remote add upstream https://github.com/ucsb-cs56-projects/cs56-music-beatbox.git; git fetch upstream; git checkout upstream/master; git checkout -b upstream_master`, then run `git merge proj02` to do the merge. It will complain that it can't do it, and then you should follow some tutorial on the internet on how to resolve it.

**Comment by fliang97** [comment]
I saw your comment on the feedback repo. There shouldn't be any problems on the visual indicator pf beats. I trying running it . Is there any chance that I can meet up with you tomorrow to fix the problem? 
By the way, I just noticed that my partner didn't specify on the Diplay Tempo Issue in proj01. We finished that in proj01 and it is worth 100 points.

**Comment by rhelmot** [comment]
ahhhhhhhh yes ok that confused me a little bit. I'll add the points.

I'll be in my lab tomorrow around 1pm. It's HFH 2114.

**Comment by fliang97** [comment]
Oh, that is so bad, I have a final on tomorrow 12pm. What time do you leave? I will try my best to be there around 1:30-2:00pm.

**Comment by rhelmot** [comment]
I'll still be around at 3.

**Comment by fliang97** [comment]
OK great! See you tomorrow.

**Comment by fliang97** [comment]
I am in HFH2114 now and I didn't see you.

**Comment by rhelmot** [comment]
Ah shit, I was planning on coming in at 3 after that conversation. I’ll be
right there.

**Pull request merged**
